### PR TITLE
Add functions to mutate a dataframe in place

### PR DESCRIPTION
**Pull request by tapiocashapeaptitude**
The goal is to be able to keep up with rapidly changing data by
writing directly into the dataframe.

Modifying dataframes
--------------------

The way that we do this is that we index into the chunk, and once we do, we have
access to a contiguous array of memory:
Step 1: index into the series we care about
Step 2: index into the chunk within the series
Step 3: modify all the data within the chunk

allowing multiple writes to a single chunk all at once helps to amortize away fixed
costs such as ocaml interop and the cost of shallow clones or something. This interface
requires that users know which chunk they care about -- otherwise, finding the
appropriate chunk would be O(n_chunks).

In this feature:
ints satisfy NativeType and are handled by this feature.
uints satisfy NativeType and are handled by this feature.
floats satisfy NativeType and are handled by this feature.

Future work:
bool chunks are represented as BooleanArray and can be mutabled.
Naivedate + Naivedatetime chunks are represented by logical types and can be
mutated by casting to i32 + i64 arrays, respectively.
use arrays instead of lists?

Not handled:
String chunks are represented by concatenating the chunk together, and are hard to
modify in-place because changing the length shifts the chunk left or right.

vstack_and_execute
------------------

The second part of this feature is vstack_and_execute. The goal here is that we
would like to be able to
1. append one row at a time from a kafka stream, with each append taking O(1) time.
2. update a value within a series in O(1) time.

We maintain a pseudo-dataframe that partitions the rows into two partitions:

1. One partition that only contains chunks of length 1000
2. One partition of length 0 <= len < 1000 that only contains chunks of length 1

Basically, all the chunks of the dataframe are length 1000, except that the remainder
is placed in partition 2. Approximately speaking, this allows us compute convert an
index within a series into a chunk index in O(1) time by computing [index % 1000]

The problem is that once partition 2 reaches length 1000, we need to rechunk those
1000 rows by popping off the last 1000 chunks, rechunking them, and popping them back
on to the dataframe. I don't know how to do that without segfaulting, so I did the
following thing instead:

1. One dataframe that only contains chunks of length 1000
2. One dataframe of length 0 <= len < 1000 that only contains chunks of length 1

When dataframe 2 exceeds size 1000, we rechunk it and vstack it onto dataframe 1.

If we want to run a sql query, we shallow clone both dataframes, vstack them on top of
each other, run the query over the union, and then destroy the shallow clones. I think
this vstack operation is O(n_chunks) but I'm not 100% sure.

Testing
-------
Expect tests for modifying int and float values, and expect tests for vstack_and_execute

### CODE REVIEW

**Comment by tapiocashapeaptitude** [comment]
@mt-caret do you know what's going on with these build failures? I think it builds fine for me locally

**Comment by mt-caret** [comment]
I'm digging into this, but I'm pretty puzzled at why we're getting weird errors here.

**Review by mt-caret — APPROVED** [review]

**Comment by mt-caret** [comment]
I haven't been able to figure out what's going on with the CI, but I don't want to block this PR for any more longer; merging.

**Comment by tapiocashapeaptitude** [comment]
🎉

**Pull request merged**
